"""Versioned form/navigation contract shared by native Android and browser portals.
Business rules and permissions are always enforced by PostgreSQL, never this catalogue.
"""
import json
from pathlib import Path
names=['Member Profile and Status','Applicant Submission and Screening Status','Activity Information and Registration','Personal Participation and Training Records','Member Operations and Equipment Borrowing','Member Dashboard and Personal Monitoring','Membership and Applicant Processing','Announcement, Event, Registration, and Attendance Management','Election Management','Equipment Inventory and Allocation Support','Training Performance Monitoring and Feedback','Financial Record Verification and Tracking','Reports, Dashboard Analytics, and Goal Monitoring','Cross-Layer System Administration and Role-Based Access Control','Shared Interclub Event Coordination']
modules=[{'number':i+1,'name':n,'tables':[],'actions':[]} for i,n in enumerate(names)]
forms={}
def form(action,label,fields,permission='account',table=None,seed=None,states=None,help=''):
 parsed=[]
 for item in fields.split(';'):
  if not item: continue
  bits=item.split(':',2); name=bits[0]; typ=bits[1] if len(bits)>1 else 'text'; extra=bits[2] if len(bits)>2 else ''
  parsed.append({'name':name,'label':name.replace('_',' ').capitalize(),'type':typ,'options':extra.split('|') if typ=='choice' else [],'source':extra if typ=='record' else '', 'optional':name.endswith('?')})
  if name.endswith('?'):parsed[-1]['name']=name[:-1];parsed[-1]['label']=parsed[-1]['label'].replace('?','')
 forms[action]={'action':action,'label':label,'fields':parsed,'permission':permission,'table':table,'seed':seed or {},'states':states or [],'help':help}
def module(n,tables,actions):modules[n-1].update(tables=tables.split(),actions=actions.split())
form('save_profile','Edit my profile','full_name;phone?',table='profiles')
form('save_application','Save application draft','full_name;phone?;student_number?;experience?:long;confirmed:boolean',table='applications')
form('submit_application','Submit application','full_name;phone?;student_number?;experience?:long;confirmed:boolean',table='applications',states=['draft','incomplete','returned_for_correction'],help='Upload required documents to your saved draft before submitting.')
form('save_renewal','Save renewal draft','information:long','account','renewals',states=['draft','returned_for_correction'])
form('request_renewal','Submit renewal information','information:long','account','renewals',states=['draft','returned_for_correction'],help='Save a draft and attach all configured renewal requirements before submitting.')
form('review_application','Review application','status:choice:under_review|incomplete|returned_for_correction|approved|rejected;remark?:long;category:choice:Regular member;requirements_verified:boolean','membership','applications',states=['pending','under_review'])
form('review_renewal','Review renewal','status:choice:approved|rejected|returned_for_correction;remark:long','membership','renewals',states=['pending'])
form('update_membership','Update official standing','status:choice:Active|Inactive|Suspended|Expired;category:choice:Regular member;remark:long','membership','memberships',{'user_id':'user_id'})
form('register_event','Register for activity','','member','events',{'event_id':'id'})
form('check_in','Enter attendance code','token','member')
form('save_event','Create or update activity','title;description:long;venue;starts_at:timestamp;ends_at:timestamp;registration_opens:timestamp;registration_closes:timestamp;capacity:number;requirements?:long;assigned_personnel?:long','activities','events')
form('publish_event','Publish activity','','activities','events')
form('archive_event','Archive activity','','activities','events')
form('publish_announcement','Publish announcement','event_id?:record:events;title;message:long','activities')
form('open_attendance','Open QR attendance period','opens_at:timestamp;closes_at:timestamp','activities','events',{'event_id':'id'})
form('record_attendance','Record manual attendance','event_id:record:events;user_id:record:member_directory;status:choice:present|absent|excused;remark:long','activities','attendance',help='Manual fallback and corrections require an explanation.')
form('request_attendance_correction','Request attendance correction','request:long','member','attendance',{'record_id':'id'})
form('review_attendance_correction','Review attendance correction','status:choice:approved|rejected;attendance_status:choice:present|absent|excused;decision:long','activities','corrections',states=['pending'])
form('save_term','Add academic term','name;sequence:number;starts_on:date;ends_on:date','elections')
form('record_residency','Record completed residency','user_id:record:member_directory;term_id:record:academic_terms;completed:boolean','elections')
form('create_election','Configure election','title;kind:choice:annual|special;term_end:date;announces_at:timestamp;candidacy_closes:timestamp;voting_opens:timestamp;voting_closes:timestamp;result_due:timestamp;threshold:number;residency_terms:number;rules:long;rules_validated:boolean;method:choice:digital|paper|external;positions:lines','elections',help='Proposal defaults: announce 4 weeks before third-term end, candidacy +3 days, voting +7 days, results within +3 days, 60% turnout, 2 consecutive completed terms. Validate the club rules before opening.')
form('file_candidacy','File candidacy','position:choice:President|Vice President;statement:long','member','elections',{'election_id':'id'},['announced'])
form('nominate_candidate','Nominate a member','user_id:record:member_directory;position:choice:President|Vice President;statement:long','member','elections',{'election_id':'id'},['announced'],help='The election officer reviews eligibility before the nomination appears on the ballot.')
form('confirm_candidate','Review candidate eligibility','confirmed:boolean;remark:long','elections','candidates')
form('confirm_voter','Confirm voter eligibility','user_id:record:member_directory;reason:long','elections','elections',{'election_id':'id'},['draft','announced'])
form('set_election_status','Advance election stage','status:choice:announced|voting|closed|archived','elections','elections')
form('record_external_results','Record paper/external results','turnout:number;results:tallies;verification:long','elections','elections',states=['closed'])
form('confirm_results','Confirm official results','confirmation:long','elections','elections',states=['closed'])
form('record_leadership','Record appointment or turnover','election_id?:record:elections;user_id?:record:member_directory;position;kind:choice:appointment|deliberation|vacancy|succession|transition;starts_on?:date;ends_on?:date;documentation:long','elections',help='This records the decision. Assign or retire system permissions separately in M14.')
form('save_equipment','Create or update equipment','label;category;specifications:long;handedness:choice:left|right|ambidextrous|not_applicable;draw_weight?:number;bow_setup?;condition:choice:serviceable|maintenance|damaged|retired;acquired_on?:date;notes?:long','equipment','equipment')
form('request_borrowing','Request equipment','equipment_id:record:equipment;event_id?:record:events;starts_at:timestamp;ends_at:timestamp;handedness:choice:left|right|not_applicable;maximum_draw_weight?:number;bow_setup?;purpose:long','member','borrowings')
form('review_borrowing','Review, release or return','status:choice:approved|rejected|returned_for_correction|released|returned;compatibility_confirmed:boolean;condition:choice:serviceable|maintenance|damaged|retired;remark:long','equipment','borrowings')
training='event_id?:record:events;training_date:date;distance:number;target_face;category;scoring_format;score:number;maximum_score:number;grouping?:long;level?;observations?:long'
form('save_personal_training','Save personal scorecard',training,'member','training_records',help='Personal entries remain distinct from official coach-validated records.')
form('save_training','Record or correct official scorecard','user_id:record:member_directory;'+training+';feedback?:long','training','training_records')
form('submit_training','Send personal scorecard for review','','member','training_records')
form('validate_training','Validate scorecard and give feedback','validation:choice:validated|returned_for_correction;feedback:long','training','training_records')
form('request_training_correction','Request scorecard correction','request:long','member','training_records',{'record_id':'id'})
form('review_training_correction','Resolve training correction','status:choice:approved|rejected;decision:long','training','corrections',states=['pending'],help='For approval, the corrected scorecard is included in this transaction.')
form('save_financial_request','Save payment, expense or reimbursement','kind:choice:payment|expense|reimbursement;purpose:long;amount:number;reference?','account','financial_records',help='Save a draft, attach proof or receipts, then submit. The app records transactions; it does not move money.')
form('submit_financial_request','Submit for financial verification','','account','financial_records',states=['draft','incomplete','returned_for_correction'])
form('approve_funds','Record prior approval','office:choice:president|finance;remark:long','funds','financial_records',states=['pending_verification'])
form('verify_financial_request','Verify financial submission','status:choice:verified|incomplete|rejected|returned_for_correction;remark:long','finance','financial_records',states=['pending_verification'])
form('assess_fee','Record fee assessment','user_id:record:member_directory;purpose;amount:number;due_on:date','finance')
form('link_fee_payment','Reconcile verified payment','payment_id:record:financial_records','finance','fee_assessments')
form('save_goal','Set measurable goal','metric:choice:active_members|applicant_conversion|attendance_rate|equipment_readiness|training_average|collection_completion;title;target:number;starts_on:date;ends_on:date','reports')
form('configure_club','Configure validated club rules','club_name;application_requirements:lines;renewal_requirements:lines;membership_categories:lines;retention_policy:long;rules_validated:boolean','administration','settings')
form('define_role','Define role and permissions','role_id;name;permissions:permissions','administration','roles')
form('assign_role','Assign time-limited officer role','user_id:record:profiles;role_id:record:roles;position;starts_at:timestamp;ends_at:timestamp;reason:long','administration','profiles',{'user_id':'id'})
form('retire_role','Retire outgoing officer access','reason:long','administration','role_assignments')
form('set_account_status','Enable or disable account','enabled:boolean;reason:long','administration','profiles',{'user_id':'id'})
form('invite_account','Create account and send invitation','email;full_name;reason:long','administration',help='This sends an invitation email. The recipient verifies the invitation code and chooses a password. It does not grant membership or officer permissions.')
form('save_partner','Add partner club','name;official_channel','interclub')
form('share_interclub_event','Share an official event','event_id:record:events;shared_details:long;requirements:long;registration_closes:timestamp;rules:long','interclub')
form('invite_partner','Invite registered representative','email;partner_id?:record:partner_clubs;role:choice:partner|coordinator','interclub','interclub_events',{'event_id':'event_id'},help='The representative first registers and verifies their account. This invitation gives access only to this event.')
form('revoke_event_access','Revoke event access','','interclub','event_access',{'event_id':'event_id'})
form('save_delegate','Register or correct own delegation','event_id:record:interclub_events;partner_id:record:partner_clubs;full_name;affiliation;category;requirements?:long;logistical_needs?:long;equipment_needs?:long','partner','delegates')
form('review_delegate','Review eligibility or check in','status:choice:eligible|incomplete|rejected|checked_in;remark:long','coordinator','delegates',{'event_id':'event_id'})
form('substitute_delegate','Approve substitution','full_name;requirements:long;remark:long','coordinator','delegates',{'event_id':'event_id'})
form('assign_delegate','Assign target or group','starts_at:timestamp;ends_at:timestamp;target_group;responsibility:long','coordinator','delegates',{'event_id':'event_id','delegate_id':'id'})
form('raise_concern','Raise coordination concern','event_id:record:interclub_events;concern:long','partner')
form('resolve_concern','Resolve concern','resolution:long','coordinator','interclub_concerns',{'event_id':'event_id'},['open'])
form('record_result','Record official result for review','result:long','coordinator','delegates',{'event_id':'event_id','delegate_id':'id'})
form('verify_result','Verify and publish result','','coordinator','interclub_results',{'event_id':'event_id'})
form('update_shared_event','Update shared event','shared_details:long;shared_venue;shared_start:timestamp;shared_end:timestamp;status:choice:preparation|active|completed','coordinator','interclub_events',{'event_id':'event_id'})
form('archive_interclub','Archive completed event','summary:long;procedures:long;agreements:long;approval_references:long;minutes:long;issues:long;evaluation:long;recommendations:long','coordinator','interclub_events',{'event_id':'event_id'},['completed'])
module(1,'profiles memberships renewals','save_profile save_renewal request_renewal')
module(2,'applications documents','save_application submit_application')
module(3,'events announcements registrations attendance','register_event check_in')
module(4,'attendance training_records corrections','save_personal_training submit_training request_attendance_correction request_training_correction')
module(5,'equipment borrowings financial_records','request_borrowing save_financial_request submit_financial_request')
module(6,'notifications documents','')
module(7,'applications memberships renewals','review_application review_renewal update_membership')
module(8,'events announcements registrations attendance_windows attendance corrections','save_event publish_event archive_event publish_announcement open_attendance record_attendance review_attendance_correction')
module(9,'elections candidates eligible_voters academic_terms member_terms leadership_records','create_election save_term record_residency file_candidacy nominate_candidate confirm_candidate confirm_voter set_election_status record_external_results confirm_results record_leadership')
module(10,'equipment borrowings equipment_history','save_equipment review_borrowing')
module(11,'training_records corrections','save_training validate_training review_training_correction')
module(12,'financial_records financial_approvals fee_assessments','save_financial_request submit_financial_request approve_funds verify_financial_request assess_fee link_fee_payment')
module(13,'goals','save_goal')
module(14,'profiles roles role_assignments settings audit_log','configure_club define_role assign_role retire_role set_account_status invite_account')
module(15,'interclub_events partner_clubs event_access delegates shared_participants interclub_assignments interclub_concerns interclub_results interclub_archives','save_partner share_interclub_event invite_partner revoke_event_access save_delegate review_delegate substitute_delegate assign_delegate raise_concern resolve_concern record_result verify_result update_shared_event archive_interclub')
forms['review_training_correction']['correction_fields']=forms['save_training']['fields']
Path('app/src/main/assets/modules.json').write_text(json.dumps({'modules':modules,'forms':forms},indent=2)+'\n')
Path('portal/modules.json').write_text(json.dumps({'modules':modules,'forms':forms},indent=2)+'\n')
